chore(#1281): reproducer for parallel access into kafka consumer
added a reproducer for https://github.com/citrusframework/citrus/issues/1281.
indeed the test which is part of the `KafkaEndpointJavaIT` throws:

```shell
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access. currentThread(name: Thread-1, id: 124) otherThread(id: 125)
```